/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package point_of_sales;


import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class R_POS extends javax.swing.JFrame {
    
    String iTax, iSubTotal, iTotal;
        double [] itemCost = new double[26];
      

    /**
     * Creates new form R_POS
     */
    public R_POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jChkApple = new javax.swing.JCheckBox();
        jTxtApple = new javax.swing.JTextField();
        jChkGinger = new javax.swing.JCheckBox();
        jTxtGinger = new javax.swing.JTextField();
        jChkRice = new javax.swing.JCheckBox();
        jTxtRice = new javax.swing.JTextField();
        jChkOrange = new javax.swing.JCheckBox();
        jTxtOrange = new javax.swing.JTextField();
        jChkBeans = new javax.swing.JCheckBox();
        jTxtBeans = new javax.swing.JTextField();
        jChkStrawberry = new javax.swing.JCheckBox();
        jTxtStrawberry = new javax.swing.JTextField();
        jChkFish = new javax.swing.JCheckBox();
        jTxtFish = new javax.swing.JTextField();
        jChkCarrot = new javax.swing.JCheckBox();
        jTxtCarrot = new javax.swing.JTextField();
        jChkTomatoes = new javax.swing.JCheckBox();
        jTxtTomatoes = new javax.swing.JTextField();
        jChkBeef = new javax.swing.JCheckBox();
        jTxtBeef = new javax.swing.JTextField();
        jChkBanana = new javax.swing.JCheckBox();
        jTxtBanana = new javax.swing.JTextField();
        jChkChicken = new javax.swing.JCheckBox();
        jTxtChicken = new javax.swing.JTextField();
        jChkIndomie = new javax.swing.JCheckBox();
        jTxtIndomie = new javax.swing.JTextField();
        jChkTurkey = new javax.swing.JCheckBox();
        jTxtTurkey = new javax.swing.JTextField();
        jChkOnions = new javax.swing.JCheckBox();
        jTxtOnions = new javax.swing.JTextField();
        jChkGarlic = new javax.swing.JCheckBox();
        jTxtGarlic = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtTax = new javax.swing.JTextField();
        jTxtSubTotal = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();
        jBtnReset = new javax.swing.JButton();
        jBtnTotal = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtReceiptArea = new javax.swing.JTextArea();
        jBtnPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBtnApple = new javax.swing.JButton();
        jBtnGinger = new javax.swing.JButton();
        jBtnOrange = new javax.swing.JButton();
        jBtnRice = new javax.swing.JButton();
        jBtnStrawberry = new javax.swing.JButton();
        jBtnBeans = new javax.swing.JButton();
        jBtnIndomie = new javax.swing.JButton();
        jBtnTurkey = new javax.swing.JButton();
        jBtnCarrot = new javax.swing.JButton();
        jBtnFish = new javax.swing.JButton();
        jBtnTomatoes = new javax.swing.JButton();
        jBtnBeef = new javax.swing.JButton();
        jBtnBanana = new javax.swing.JButton();
        jBtnChicken = new javax.swing.JButton();
        jBtnGarlic = new javax.swing.JButton();
        jBtnOnions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 730));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jChkApple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkApple.setText("Apple");
        jChkApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkAppleActionPerformed(evt);
            }
        });

        jTxtApple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtApple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtApple.setText("0");
        jTxtApple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtAppleKeyTyped(evt);
            }
        });

        jChkGinger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkGinger.setText("Ginger");
        jChkGinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkGingerActionPerformed(evt);
            }
        });

        jTxtGinger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtGinger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtGinger.setText("0");
        jTxtGinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGingerActionPerformed(evt);
            }
        });
        jTxtGinger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtGingerKeyTyped(evt);
            }
        });

        jChkRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkRice.setText("Rice");
        jChkRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRiceActionPerformed(evt);
            }
        });

        jTxtRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtRice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtRice.setText("0");
        jTxtRice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtRiceKeyTyped(evt);
            }
        });

        jChkOrange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkOrange.setText("Orange");
        jChkOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkOrangeActionPerformed(evt);
            }
        });

        jTxtOrange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtOrange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtOrange.setText("0");
        jTxtOrange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtOrangeKeyTyped(evt);
            }
        });

        jChkBeans.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBeans.setText("Beans");
        jChkBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBeansActionPerformed(evt);
            }
        });

        jTxtBeans.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtBeans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtBeans.setText("0");
        jTxtBeans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtBeansKeyTyped(evt);
            }
        });

        jChkStrawberry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkStrawberry.setText("Strawberry");
        jChkStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkStrawberryActionPerformed(evt);
            }
        });

        jTxtStrawberry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtStrawberry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtStrawberry.setText("0");
        jTxtStrawberry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtStrawberryKeyTyped(evt);
            }
        });

        jChkFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkFish.setText("Fish");
        jChkFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkFishActionPerformed(evt);
            }
        });

        jTxtFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFish.setText("0");
        jTxtFish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFishKeyTyped(evt);
            }
        });

        jChkCarrot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCarrot.setText("Carrot");
        jChkCarrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCarrotActionPerformed(evt);
            }
        });

        jTxtCarrot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtCarrot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCarrot.setText("0");
        jTxtCarrot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCarrotKeyTyped(evt);
            }
        });

        jChkTomatoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkTomatoes.setText("Tomatoes");
        jChkTomatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkTomatoesActionPerformed(evt);
            }
        });

        jTxtTomatoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtTomatoes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTomatoes.setText("0");
        jTxtTomatoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTomatoesKeyTyped(evt);
            }
        });

        jChkBeef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBeef.setText("Beef");
        jChkBeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBeefActionPerformed(evt);
            }
        });

        jTxtBeef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtBeef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtBeef.setText("0");
        jTxtBeef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtBeefKeyTyped(evt);
            }
        });

        jChkBanana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBanana.setText("Banana");
        jChkBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBananaActionPerformed(evt);
            }
        });

        jTxtBanana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtBanana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtBanana.setText("0");
        jTxtBanana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtBananaKeyTyped(evt);
            }
        });

        jChkChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkChicken.setText("Chicken");
        jChkChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChickenActionPerformed(evt);
            }
        });

        jTxtChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtChicken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtChicken.setText("0");
        jTxtChicken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtChickenKeyTyped(evt);
            }
        });

        jChkIndomie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIndomie.setText("Indomie");
        jChkIndomie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIndomieActionPerformed(evt);
            }
        });

        jTxtIndomie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtIndomie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtIndomie.setText("0");
        jTxtIndomie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIndomieKeyTyped(evt);
            }
        });

        jChkTurkey.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkTurkey.setText("Turkey");
        jChkTurkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkTurkeyActionPerformed(evt);
            }
        });

        jTxtTurkey.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtTurkey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTurkey.setText("0");
        jTxtTurkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTurkeyKeyTyped(evt);
            }
        });

        jChkOnions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkOnions.setText("Onions");
        jChkOnions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkOnionsActionPerformed(evt);
            }
        });

        jTxtOnions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtOnions.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtOnions.setText("0");
        jTxtOnions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtOnionsKeyTyped(evt);
            }
        });

        jChkGarlic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkGarlic.setText("Garlic");
        jChkGarlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkGarlicActionPerformed(evt);
            }
        });

        jTxtGarlic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtGarlic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtGarlic.setText("0");
        jTxtGarlic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtGarlicKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkStrawberry)
                                    .addComponent(jChkCarrot)
                                    .addComponent(jChkBanana))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtStrawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtTomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtIndomie, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtOnions, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkOrange)
                                    .addComponent(jChkApple))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtOrange)
                                    .addComponent(jTxtApple))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkRice)
                                    .addComponent(jChkGinger))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtGinger, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(jTxtRice)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkBeans)
                                    .addComponent(jChkFish))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtBeans, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(jTxtFish)))
                            .addComponent(jChkBeef)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChkIndomie)
                            .addComponent(jChkOnions)
                            .addComponent(jChkTomatoes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jChkChicken)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtBeef, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkTurkey)
                                    .addComponent(jChkGarlic))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtTurkey, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkApple)
                    .addComponent(jTxtApple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkGinger)
                    .addComponent(jTxtGinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkOrange)
                    .addComponent(jTxtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkRice)
                    .addComponent(jTxtRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkStrawberry)
                    .addComponent(jTxtStrawberry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkBeans)
                    .addComponent(jTxtBeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChkFish)
                            .addComponent(jTxtFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChkCarrot)
                            .addComponent(jTxtCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jChkTomatoes)
                        .addComponent(jTxtBeef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtTomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkBeef))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jChkChicken)
                    .addComponent(jChkBanana))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIndomie)
                    .addComponent(jTxtIndomie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkTurkey)
                    .addComponent(jTxtTurkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkOnions)
                    .addComponent(jTxtOnions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkGarlic)
                    .addComponent(jTxtGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Sub-Total");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tax");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtTax.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTax.setText("0.00");

        jTxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtSubTotal.setText("0.00");

        jTxtTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTotal.setText("0.00");

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jTxtReceiptArea.setColumns(20);
        jTxtReceiptArea.setRows(5);
        jScrollPane1.setViewportView(jTxtReceiptArea);

        jBtnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnPrint.setText("Print");
        jBtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBtnTotal)
                .addGap(18, 18, 18)
                .addComponent(jBtnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnPrint)
                .addGap(18, 18, 18)
                .addComponent(jBtnExit)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReset)
                    .addComponent(jBtnExit)
                    .addComponent(jBtnTotal)
                    .addComponent(jBtnPrint))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Point of Sale System");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Cost of Items and Receipt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnApple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnApple.setText("Apple");
        jBtnApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAppleActionPerformed(evt);
            }
        });

        jBtnGinger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnGinger.setText("Ginger");
        jBtnGinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGingerActionPerformed(evt);
            }
        });

        jBtnOrange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOrange.setText("Orange");
        jBtnOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOrangeActionPerformed(evt);
            }
        });

        jBtnRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnRice.setText("Rice");
        jBtnRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRiceActionPerformed(evt);
            }
        });

        jBtnStrawberry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnStrawberry.setText("Strawberry");
        jBtnStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStrawberryActionPerformed(evt);
            }
        });

        jBtnBeans.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnBeans.setText("Beans");
        jBtnBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBeansActionPerformed(evt);
            }
        });

        jBtnIndomie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnIndomie.setText("Indomie");
        jBtnIndomie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIndomieActionPerformed(evt);
            }
        });

        jBtnTurkey.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnTurkey.setText("Turkey");
        jBtnTurkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTurkeyActionPerformed(evt);
            }
        });

        jBtnCarrot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnCarrot.setText("Carrot");
        jBtnCarrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCarrotActionPerformed(evt);
            }
        });

        jBtnFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnFish.setText("Fish");
        jBtnFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFishActionPerformed(evt);
            }
        });

        jBtnTomatoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnTomatoes.setText("Tomatoes");
        jBtnTomatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTomatoesActionPerformed(evt);
            }
        });

        jBtnBeef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnBeef.setText("Beef");
        jBtnBeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBeefActionPerformed(evt);
            }
        });

        jBtnBanana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnBanana.setText("Banana");
        jBtnBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBananaActionPerformed(evt);
            }
        });

        jBtnChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnChicken.setText("Chicken");
        jBtnChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChickenActionPerformed(evt);
            }
        });

        jBtnGarlic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnGarlic.setText("Garlic");
        jBtnGarlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGarlicActionPerformed(evt);
            }
        });

        jBtnOnions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOnions.setText("Onions");
        jBtnOnions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOnionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnTomatoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnBeef, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnApple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnGinger, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnOrange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnStrawberry, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jBtnCarrot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnBeans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnRice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnFish, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnIndomie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnTurkey, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnBanana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnOnions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnChicken)
                                .addGap(14, 14, 14))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApple)
                    .addComponent(jBtnGinger))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOrange)
                    .addComponent(jBtnRice))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnStrawberry)
                    .addComponent(jBtnBeans))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCarrot)
                    .addComponent(jBtnFish))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTomatoes)
                    .addComponent(jBtnBeef))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBanana)
                    .addComponent(jBtnChicken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIndomie)
                    .addComponent(jBtnTurkey))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOnions)
                    .addComponent(jBtnGarlic))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Categories");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"COnfirm if you want to exit", "Point of Sales",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        jChkApple.setSelected(false);
        jTxtApple.setText("0");
        jChkOrange.setSelected(false);
        jTxtOrange.setText("0");
        jChkStrawberry.setSelected(false);
        jTxtStrawberry.setText("0");
        jChkCarrot.setSelected(false);
        jTxtCarrot.setText("0");
        jChkFish.setSelected(false);
        jTxtFish.setText("0");
        jChkTomatoes.setSelected(false);
        jTxtTomatoes.setText("0");
        jChkBanana.setSelected(false);
        jTxtBanana.setText("0");
        jChkIndomie.setSelected(false);
        jTxtIndomie.setText("0");
        jChkOnions.setSelected(false);
        jTxtOnions.setText("0");
        jChkGinger.setSelected(false);
        jTxtGinger.setText("0");
        jChkRice.setSelected(false);
        jTxtRice.setText("0");
        jChkBeans.setSelected(false);
        jTxtBeans.setText("0");
        jChkBeef.setSelected(false);
        jTxtBeef.setText("0");
        jChkChicken.setSelected(false);
        jTxtChicken.setText("0");
        jChkTurkey.setSelected(false);
        jTxtTurkey.setText("0");
        jChkGarlic.setSelected(false);
        jTxtGarlic.setText("0");
        
        jChkApple.setEnabled(false);
        jChkOrange.setEnabled(false);
        jChkStrawberry.setEnabled(false);
        jChkCarrot.setEnabled(false);
        jChkTomatoes.setEnabled(false);
        jChkBanana.setEnabled(false);
        jChkIndomie.setEnabled(false);
        jChkOnions.setEnabled(false);
        jChkGinger.setEnabled(false);
        jChkRice.setEnabled(false);
        jChkBeans.setEnabled(false);
        jChkFish.setEnabled(false);
        jChkBeef.setEnabled(false);
        jChkChicken.setEnabled(false);
        jChkTurkey.setEnabled(false);
        jChkGarlic.setEnabled(false);
        
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jChkAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkAppleActionPerformed
        // TODO add your handling code here:
        if (jChkApple.isSelected()) {
            jTxtApple.setEnabled(true);
            jTxtApple.setText("");
            jTxtApple.requestFocus();
        }
        else {
            jTxtApple.setEnabled(false);
        }
    }//GEN-LAST:event_jChkAppleActionPerformed

    private void jTxtAppleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtAppleKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtAppleKeyTyped

    private void jTxtGingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGingerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGingerActionPerformed

    private void jTxtGingerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtGingerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtGingerKeyTyped

    private void jTxtOrangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtOrangeKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtOrangeKeyTyped

    private void jTxtRiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRiceKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtRiceKeyTyped

    private void jTxtStrawberryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtStrawberryKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtStrawberryKeyTyped

    private void jTxtBeansKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBeansKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtBeansKeyTyped

    private void jTxtCarrotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCarrotKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCarrotKeyTyped

    private void jTxtFishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFishKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtFishKeyTyped

    private void jTxtTomatoesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTomatoesKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtTomatoesKeyTyped

    private void jTxtBeefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBeefKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtBeefKeyTyped

    private void jTxtBananaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBananaKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtBananaKeyTyped

    private void jTxtChickenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtChickenKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtChickenKeyTyped

    private void jTxtIndomieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIndomieKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtIndomieKeyTyped

    private void jTxtTurkeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTurkeyKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtTurkeyKeyTyped

    private void jTxtOnionsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtOnionsKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtOnionsKeyTyped

    private void jTxtGarlicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtGarlicKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        || (iNumber == KeyEvent.VK_BACK_SPACE)
        || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtGarlicKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTxtApple.setEnabled(false);
        jTxtOrange.setEnabled(false);
        jTxtStrawberry.setEnabled(false);
        jTxtCarrot.setEnabled(false);
        jTxtTomatoes.setEnabled(false);
        jTxtBanana.setEnabled(false);
        jTxtIndomie.setEnabled(false);
        jTxtOnions.setEnabled(false);
        jTxtGinger.setEnabled(false);
        jTxtRice.setEnabled(false);
        jTxtBeans.setEnabled(false);
        jTxtFish.setEnabled(false);
        jTxtBeef.setEnabled(false);
        jTxtChicken.setEnabled(false);
        jTxtTurkey.setEnabled(false);
        jTxtGarlic.setEnabled(false);
        jTxtReceiptArea.setEnabled(false);
        
         jChkApple.setEnabled(false);
        jChkOrange.setEnabled(false);
        jChkStrawberry.setEnabled(false);
        jChkCarrot.setEnabled(false);
        jChkTomatoes.setEnabled(false);
        jChkBanana.setEnabled(false);
        jChkIndomie.setEnabled(false);
        jChkOnions.setEnabled(false);
        jChkGinger.setEnabled(false);
        jChkRice.setEnabled(false);
        jChkBeans.setEnabled(false);
        jChkFish.setEnabled(false);
        jChkBeef.setEnabled(false);
        jChkChicken.setEnabled(false);
        jChkTurkey.setEnabled(false);
        jChkGarlic.setEnabled(false);
        
        jTxtTax.setEnabled(false);
        jTxtTotal.setEnabled(false);
        jTxtSubTotal.setEnabled(false);
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jBtnAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAppleActionPerformed
        // TODO add your handling code here:
        jChkApple.setEnabled(true);
    }//GEN-LAST:event_jBtnAppleActionPerformed

    private void jBtnGingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGingerActionPerformed
        // TODO add your handling code here:
        jChkGinger.setEnabled(true);
    }//GEN-LAST:event_jBtnGingerActionPerformed

    private void jBtnOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOrangeActionPerformed
        // TODO add your handling code here:
        jChkOrange.setEnabled(true);
    }//GEN-LAST:event_jBtnOrangeActionPerformed

    private void jBtnRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRiceActionPerformed
        // TODO add your handling code here:
        jChkRice.setEnabled(true);
    }//GEN-LAST:event_jBtnRiceActionPerformed

    private void jBtnStrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStrawberryActionPerformed
        // TODO add your handling code here:
        jChkStrawberry.setEnabled(true);
    }//GEN-LAST:event_jBtnStrawberryActionPerformed

    private void jBtnBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBeansActionPerformed
        // TODO add your handling code here:
        jChkBeans.setEnabled(true);
    }//GEN-LAST:event_jBtnBeansActionPerformed

    private void jBtnCarrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCarrotActionPerformed
        // TODO add your handling code here:
        jChkCarrot.setEnabled(true);
    }//GEN-LAST:event_jBtnCarrotActionPerformed

    private void jBtnFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFishActionPerformed
        // TODO add your handling code here:
        jChkFish.setEnabled(true);
    }//GEN-LAST:event_jBtnFishActionPerformed

    private void jBtnTomatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTomatoesActionPerformed
        // TODO add your handling code here:
        jChkTomatoes.setEnabled(true);
    }//GEN-LAST:event_jBtnTomatoesActionPerformed

    private void jBtnBeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBeefActionPerformed
        // TODO add your handling code here:
        jChkBeef.setEnabled(true);
    }//GEN-LAST:event_jBtnBeefActionPerformed

    private void jBtnBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBananaActionPerformed
        // TODO add your handling code here:
        jChkBanana.setEnabled(true);
    }//GEN-LAST:event_jBtnBananaActionPerformed

    private void jBtnChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChickenActionPerformed
        // TODO add your handling code here:
        jChkChicken.setEnabled(true);
    }//GEN-LAST:event_jBtnChickenActionPerformed

    private void jBtnIndomieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIndomieActionPerformed
        // TODO add your handling code here:
        jChkIndomie.setEnabled(true);
    }//GEN-LAST:event_jBtnIndomieActionPerformed

    private void jBtnTurkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTurkeyActionPerformed
        // TODO add your handling code here:
        jChkTurkey.setEnabled(true);
    }//GEN-LAST:event_jBtnTurkeyActionPerformed

    private void jBtnOnionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOnionsActionPerformed
        // TODO add your handling code here:
        jChkOnions.setEnabled(true);
    }//GEN-LAST:event_jBtnOnionsActionPerformed

    private void jBtnGarlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGarlicActionPerformed
        // TODO add your handling code here:
        jChkGarlic.setEnabled(true);
    }//GEN-LAST:event_jBtnGarlicActionPerformed

    private void jChkGingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkGingerActionPerformed
        // TODO add your handling code here:
        if (jChkGinger.isSelected()) {
            jTxtGinger.setEnabled(true);
            jTxtGinger.setText("");
            jTxtGinger.requestFocus();
        }
        else {
            jTxtGinger.setEnabled(false);
        }
    }//GEN-LAST:event_jChkGingerActionPerformed

    private void jChkOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkOrangeActionPerformed
        // TODO add your handling code here:
         if (jChkOrange.isSelected()) {
            jTxtOrange.setEnabled(true);
            jTxtOrange.setText("");
            jTxtOrange.requestFocus();
        }
        else {
            jTxtOrange.setEnabled(false);
        }
    }//GEN-LAST:event_jChkOrangeActionPerformed

    private void jChkRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRiceActionPerformed
        // TODO add your handling code here:
        if (jChkRice.isSelected()) {
            jTxtRice.setEnabled(true);
            jTxtRice.setText("");
            jTxtRice.requestFocus();
        }
        else {
            jTxtRice.setEnabled(false);
        }
    }//GEN-LAST:event_jChkRiceActionPerformed

    private void jChkStrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkStrawberryActionPerformed
        // TODO add your handling code here:
         if (jChkStrawberry.isSelected()) {
            jTxtStrawberry.setEnabled(true);
            jTxtStrawberry.setText("");
            jTxtStrawberry.requestFocus();
        }
        else {
            jTxtStrawberry.setEnabled(false);
        }
    }//GEN-LAST:event_jChkStrawberryActionPerformed

    private void jChkBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBeansActionPerformed
        // TODO add your handling code here:
        if (jChkBeans.isSelected()) {
            jTxtBeans.setEnabled(true);
            jTxtBeans.setText("");
            jTxtBeans.requestFocus();
        }
        else {
            jTxtBeans.setEnabled(false);
        }
    }//GEN-LAST:event_jChkBeansActionPerformed

    private void jChkCarrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCarrotActionPerformed
        // TODO add your handling code here:
        if (jChkCarrot.isSelected()) {
            jTxtCarrot.setEnabled(true);
            jTxtCarrot.setText("");
            jTxtCarrot.requestFocus();
        }
        else {
            jTxtCarrot.setEnabled(false);
        }
    }//GEN-LAST:event_jChkCarrotActionPerformed

    private void jChkFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkFishActionPerformed
        // TODO add your handling code here:
         if (jChkFish.isSelected()) {
            jTxtFish.setEnabled(true);
            jTxtFish.setText("");
            jTxtFish.requestFocus();
        }
        else {
            jTxtFish.setEnabled(false);
        }
    }//GEN-LAST:event_jChkFishActionPerformed

    private void jChkTomatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkTomatoesActionPerformed
        // TODO add your handling code here:
         if (jChkTomatoes.isSelected()) {
            jTxtTomatoes.setEnabled(true);
            jTxtTomatoes.setText("");
            jTxtTomatoes.requestFocus();
        }
        else {
            jTxtTomatoes.setEnabled(false);
        }
    }//GEN-LAST:event_jChkTomatoesActionPerformed

    private void jChkBeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBeefActionPerformed
        // TODO add your handling code here:
        if (jChkBeef.isSelected()) {
            jTxtBeef.setEnabled(true);
            jTxtBeef.setText("");
            jTxtBeef.requestFocus();
        }
        else {
            jTxtBeef.setEnabled(false);
        }
    }//GEN-LAST:event_jChkBeefActionPerformed

    private void jChkBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBananaActionPerformed
        // TODO add your handling code here:
         if (jChkBanana.isSelected()) {
            jTxtBanana.setEnabled(true);
            jTxtBanana.setText("");
            jTxtBanana.requestFocus();
        }
        else {
            jTxtBanana.setEnabled(false);
        }
    }//GEN-LAST:event_jChkBananaActionPerformed

    private void jChkChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChickenActionPerformed
        // TODO add your handling code here:
         if (jChkChicken.isSelected()) {
            jTxtChicken.setEnabled(true);
            jTxtChicken.setText("");
            jTxtChicken.requestFocus();
        }
        else {
            jTxtChicken.setEnabled(false);
        }
    }//GEN-LAST:event_jChkChickenActionPerformed

    private void jChkIndomieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIndomieActionPerformed
        // TODO add your handling code here:
         if (jChkIndomie.isSelected()) {
            jTxtIndomie.setEnabled(true);
            jTxtIndomie.setText("");
            jTxtIndomie.requestFocus();
        }
        else {
            jTxtIndomie.setEnabled(false);
        }
    }//GEN-LAST:event_jChkIndomieActionPerformed

    private void jChkTurkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkTurkeyActionPerformed
        // TODO add your handling code here:
         if (jChkTurkey.isSelected()) {
            jTxtTurkey.setEnabled(true);
            jTxtTurkey.setText("");
            jTxtTurkey.requestFocus();
        }
        else {
            jTxtTurkey.setEnabled(false);
        }
    }//GEN-LAST:event_jChkTurkeyActionPerformed

    private void jChkOnionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkOnionsActionPerformed
        // TODO add your handling code here:
         if (jChkOnions.isSelected()) {
            jTxtOnions.setEnabled(true);
            jTxtOnions.setText("");
            jTxtOnions.requestFocus();
        }
        else {
            jTxtOnions.setEnabled(false);
        }
    }//GEN-LAST:event_jChkOnionsActionPerformed

    private void jChkGarlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkGarlicActionPerformed
        // TODO add your handling code here:
         if (jChkGarlic.isSelected()) {
            jTxtGarlic.setEnabled(true);
            jTxtGarlic.setText("");
            jTxtGarlic.requestFocus();
        }
        else {
            jTxtGarlic.setEnabled(false);
        }
    }//GEN-LAST:event_jChkGarlicActionPerformed

    private void jBtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrintActionPerformed
        try {
            // TODO add your handling code here:
            jTxtReceiptArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(R_POS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnPrintActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:
        itemCost[0] = Double.parseDouble(jTxtApple.getText()) * 1.5;
        itemCost[1] = Double.parseDouble(jTxtOrange.getText()) * 1.5;
        itemCost[2] = Double.parseDouble(jTxtStrawberry.getText()) * 1.5;
        itemCost[3] = Double.parseDouble(jTxtCarrot.getText()) * 1.5;
        itemCost[4] = Double.parseDouble(jTxtTomatoes.getText()) * 1.5;
        itemCost[5] = Double.parseDouble(jTxtBanana.getText()) * 1.5;
        itemCost[6] = Double.parseDouble(jTxtIndomie.getText()) * 1.5;
        itemCost[7] = Double.parseDouble(jTxtOnions.getText()) * 1.5;
        itemCost[8] = Double.parseDouble(jTxtGinger.getText()) * 1.5;
        itemCost[9] = Double.parseDouble(jTxtRice.getText()) * 1.5;
        itemCost[10] = Double.parseDouble(jTxtBeans.getText()) * 1.5;
        itemCost[11] = Double.parseDouble(jTxtFish.getText()) * 1.5;
        itemCost[12] = Double.parseDouble(jTxtBeef.getText()) * 1.5;
        itemCost[13] = Double.parseDouble(jTxtChicken.getText()) * 1.5;
        itemCost[14] = Double.parseDouble(jTxtTurkey.getText()) * 1.5;
        itemCost[15] = Double.parseDouble(jTxtGarlic.getText()) * 1.5;
        
        itemCost[16] = itemCost[0] + itemCost[1] + itemCost[2] + itemCost[3];
        itemCost[17] = itemCost[4] + itemCost[5] + itemCost[6] + itemCost[7];
        itemCost[18] = itemCost[8] + itemCost[9] + itemCost[10] + itemCost[11];
        itemCost[19] = itemCost[12]+ itemCost[13] + itemCost[14] + itemCost[15];
        
        iTax = String.format("₦ %.2f", itemCost[15] /100);
        iSubTotal = String.format("₦ %.2f", itemCost[15]);
        iTotal = String.format("₦ %.2f", itemCost[15] + (itemCost[15] /100));
        
        jTxtTax.setText(iTax);
        jTxtSubTotal.setText(iSubTotal);
        jTxtTotal.setText(iTotal);
        
        //////////////////////////////////////////////////////////////
        jTxtReceiptArea.setEnabled(true);
        //===========================================================
        int refs = 1325 + (int)Math.random()*4238;
        //int ref = (refs);
        //===========================================================
            Calendar timer =  Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
            tTime.format(timer.getTime());
            SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
            tDate.format(timer.getTime());
        //===========================================================
            jTxtReceiptArea.append("\tJegudu-Jera Super Market\n" +
            "Reference:\t\t\t\t" + refs +
             "\n===========================================\t "+ 
              "\n===========================================\t"+
                    "nTax:\t\t\t\t"+iTax +
                    "nSubTotal:\t\t\t\t"+iSubTotal +
                    "nTotal:\t\t\t\t"+ iTotal +
                "\n===========================================\t" +
                 "\nDate: "+ tDate.format(timer.getTime() +
                         "\nThank you for your patronage"));
    }//GEN-LAST:event_jBtnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(R_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(R_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(R_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(R_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new R_POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApple;
    private javax.swing.JButton jBtnBanana;
    private javax.swing.JButton jBtnBeans;
    private javax.swing.JButton jBtnBeef;
    private javax.swing.JButton jBtnCarrot;
    private javax.swing.JButton jBtnChicken;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnFish;
    private javax.swing.JButton jBtnGarlic;
    private javax.swing.JButton jBtnGinger;
    private javax.swing.JButton jBtnIndomie;
    private javax.swing.JButton jBtnOnions;
    private javax.swing.JButton jBtnOrange;
    private javax.swing.JButton jBtnPrint;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnRice;
    private javax.swing.JButton jBtnStrawberry;
    private javax.swing.JButton jBtnTomatoes;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JButton jBtnTurkey;
    private javax.swing.JCheckBox jChkApple;
    private javax.swing.JCheckBox jChkBanana;
    private javax.swing.JCheckBox jChkBeans;
    private javax.swing.JCheckBox jChkBeef;
    private javax.swing.JCheckBox jChkCarrot;
    private javax.swing.JCheckBox jChkChicken;
    private javax.swing.JCheckBox jChkFish;
    private javax.swing.JCheckBox jChkGarlic;
    private javax.swing.JCheckBox jChkGinger;
    private javax.swing.JCheckBox jChkIndomie;
    private javax.swing.JCheckBox jChkOnions;
    private javax.swing.JCheckBox jChkOrange;
    private javax.swing.JCheckBox jChkRice;
    private javax.swing.JCheckBox jChkStrawberry;
    private javax.swing.JCheckBox jChkTomatoes;
    private javax.swing.JCheckBox jChkTurkey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtApple;
    private javax.swing.JTextField jTxtBanana;
    private javax.swing.JTextField jTxtBeans;
    private javax.swing.JTextField jTxtBeef;
    private javax.swing.JTextField jTxtCarrot;
    private javax.swing.JTextField jTxtChicken;
    private javax.swing.JTextField jTxtFish;
    private javax.swing.JTextField jTxtGarlic;
    private javax.swing.JTextField jTxtGinger;
    private javax.swing.JTextField jTxtIndomie;
    private javax.swing.JTextField jTxtOnions;
    private javax.swing.JTextField jTxtOrange;
    private javax.swing.JTextArea jTxtReceiptArea;
    private javax.swing.JTextField jTxtRice;
    private javax.swing.JTextField jTxtStrawberry;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField jTxtTax;
    private javax.swing.JTextField jTxtTomatoes;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextField jTxtTurkey;
    // End of variables declaration//GEN-END:variables
}
